default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_development
  username: api
  password: 'farmer' # Replace with the actual password you set for the api user
  host: localhost
  port: 5432
  sslmode: prefer

test:
  <<: *default
  database: api_test
  username: api
  password: 'farmer' # Replace with the actual password you set for the api user
  host: localhost
  port: 5432
  sslmode: prefer

production:
  <<: *default
  database: api_production
  username: api
  password: 'farmer' # Replace with the actual password you set for the api user
  host: localhost
  port: 5432
  sslmode: prefer